# Generated by Django 5.2.5 on 2025-08-29 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Water', 'Water'), ('Bottle', 'Bottle')], max_length=20)),
                ('item', models.CharField(choices=[('20L', '20L'), ('10L', '10L'), ('5L', '5L'), ('1L', '1L'), ('1L Pack', '1L Pack'), ('500ML Pack', '500ML Pack'), ('20L Bottle', '20L Bottle'), ('10L Bottle', '10L Bottle'), ('5L Bottle', '5L Bottle')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
