# Generated by Django 5.2.5 on 2025-10-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='closing_balance',
            new_name='cumulative_balance',
        ),
    ]
