# Generated by Django 5.2.6 on 2025-09-18 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sale_payment_method_alter_sale_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paid_to', models.CharField(max_length=255)),
                ('charged_to', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('receipt_no', models.CharField(max_length=50)),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_injected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
