# Generated by Django 5.2.5 on 2025-09-23 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_expense_category_remove_expense_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
