# Generated by Django 5.2.6 on 2025-09-29 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sale_payment_status_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('MPesa', 'MPesa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Delivery', 'Delivery'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=20),
        ),
    ]
